
[AGGREGATION]
YEARS = [2007]
PROVIDERS = ["NMDC"]
LIST_DIR = "./lists"

[MAPPING]
DATE_MIN = "20070101"
DATE_MAX = "20071231"
BIN_SIZE = [0.5,1.5]
VARIABLE="CPHL"
PROVIDERS=["IMR"]
DEPTH_AGGREGATION="top"
BIN_AGGREGATION="count"

[UTILS]
VERBOSE = 2
SAVING_DIR = "/home/gaerig/Projects/bgc-data-processing/bgc_data"

[PROVIDERS]
    [PROVIDERS.ARGO]
    PATH = "/var/sat/S23Eddy/Data/Argo/INSITU_GLO_BGC_REP"
    CATEGORY = "float"
    EXCLUDE = [
        "GL_PR_PF_6900798.nc",
        "GL_PR_PF_5903592.nc",
        "GL_PR_PF_5903887.nc",
        "GL_PR_PF_6900796.nc",
        "GL_PR_PF_6900797.nc",
        "GL_PR_PF_6900799.nc",
        "GL_PR_PF_6903551.nc",
        "GL_PR_PF_6903567.nc",
        "GL_PR_PF_6903574.nc",
        "GL_PR_PF_6903575.nc",
        "GL_PR_PF_6903578.nc",
        "GL_PR_PF_6903579.nc"
    ]
    [PROVIDERS.CLIVAR]
    PATH = "/mnt/data02/gaerig/synthesis/CLIVAR/data"
    CATEGORY = "in_situ"
    EXCLUDE = []
    [PROVIDERS.GLODAPv2]
    PATH = "/mnt/data02/gaerig/synthesis/GLODAPv2/data"
    CATEGORY = "in_situ"
    EXCLUDE = []
    [PROVIDERS.GLODAP_2019]
    PATH = "/mnt/data02/gaerig/synthesis/GLODAPv2.2019/data"
    CATEGORY = "in_situ"
    EXCLUDE = []
    [PROVIDERS.GLODAP_2022]
    PATH = "/mnt/data02/gaerig/synthesis/GLODAPv2.2022/data"
    CATEGORY = "in_situ"
    EXCLUDE = []
    [PROVIDERS.ICES]
    PATH = "/mnt/data02/gaerig/synthesis/ICES/data"
    CATEGORY = "in_situ"
    EXCLUDE = []
    [PROVIDERS.IMR]
    PATH = "/mnt/data02/gaerig/synthesis/IMR/data"
    CATEGORY = "in_situ"
    EXCLUDE = []
    [PROVIDERS.NMDC]
    PATH = "/mnt/data02/gaerig/synthesis/NMDC/data"
    CATEGORY = "in_situ"
    EXCLUDE = []
    [PROVIDERS.CMEMS]
    PATH = "/mnt/data02/gaerig/synthesis/CMEMS/history/nutrients/BO"
    CATEGORY = "in_situ"
    EXCLUDE = []
