[LOADING]
ARGO = "/var/sat/S23Eddy/Data/Argo/INSITU_GLO_BGC_REP"
CLIVAR = "/mnt/data02/gaerig/synthesis/CLIVAR/data"
GLODAPv2 = "/mnt/data02/gaerig/synthesis/GLODAPv2/data"
GLODAP_2019 = "/mnt/data02/gaerig/synthesis/GLODAPv2.2019/data"
GLODAP_2022 = "/mnt/data02/gaerig/synthesis/GLODAPv2.2022/data"
ICES = "/mnt/data02/gaerig/synthesis/ICES/data"
IMR = "/mnt/data02/gaerig/synthesis/IMR/data"
NMDC = "/mnt/data02/gaerig/synthesis/NMDC/data"
LIST_DIR = "./lists"
[SAVING]
FILES_DIR = "/home/gaerig/Projects/bgc-data-processing/bgc_data"
