site_name: BGC-DATA-PROCESSING
# Add repository metadate for more integration and ease-of-use
repo_name: bgc-data-processing
repo_url: https://github.com/grigaut/bgc-data-processing

theme:
  name: "material"
  logo: assets/logo/NERSC.png
  favicon: assets/logo/NERSC.png
  palette:
    primary: red
  features:
    - navigation.tabs               # Tabs
    - navigation.tabs.sticky        # Above tabs stay displayed
    - navigation.indexes            # Attach documents to sections
    - navigation.instant
    - navigation.footer
    - navigation.top                # Scroll back to top button
    - content.code.annotate         # Admonitions
    - content.code.copy             # copy code block
    - watch:
        - "bgc_data_processing"

nav:
  - Getting Started:
    - index.md
  - Scripts:
    - scripts/index.md
    - scripts/save_data.md
    - scripts/plot_mesh.md
    - scripts/plot_profile.md
    - scripts/plot_interactive.md
    - scripts/plot_ts_diagram.md
    - scripts/plot_var_boxplot.md
    - scripts/plot_var_histogram.md
    - scripts/plot_var_pressure.md
    - scripts/match_hycom_obs.md
  - How does it work ?:
    - how_it_works/index.md
    - how_it_works/variables.md
    - how_it_works/loading.md
    - how_it_works/plotting.md
    - how_it_works/closest_point_find.md
  - Examples:
    - examples/index.md
    - examples/boundaries.md
    - examples/plot.md
  - Virtual Environment:
    - virtual_env/index.md
  - Contributing:
    - contributing/index.md
  - Code Reference: reference/

plugins:
  - autorefs
  - search                                      # Search bar
  - macros                                      # Use variables in documentation
  - literate-nav:
      nav_file: SUMMARY.md                      # To auto-generate paths
  - gen-files:
      scripts:
        - docs/automation/pages_generator.py    # To auto generate 'Code Reference' Section
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy              # To parse docstrings
            docstring_section_style: spacy
            heading_level: 3
            show_root_toc_entry: false
            show_if_no_docstring: true
            showsubmodules: true


markdown_extensions:
  - admonition
  - pymdownx.superfences      # code blocks
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true   # Tabs
  - footnotes
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


extra:
  repo_tree: https://github.com/grigaut/bgc-data-processing/tree/main
  repo_blob: https://github.com/grigaut/bgc-data-processing/blob/main
