site_name: BGC-DATA-PROCESSING
# Add repository metadate for more integration and ease-of-use
repo_name: bgc-data-processing
repo_url: https://github.com/grigaut/bgc-data-processing

theme:
  name: "material"
  logo: assets/logo/NERSC.png
  favicon: assets/logo/NERSC.png
  palette:
    primary: blue
  features:
    - navigation.tabs               # Tabs
    - navigation.tabs.sticky        # Above tabs stay displayed
    - navigation.indexes            # Attach documents to sections
    - navigation.instant
    - navigation.top                # Scroll back to top button
    - watch:
        - "bgc_data_processing"

nav:
  - Getting Started:
    - index.md
  - How does it work ?:
    - how_it_works/index.md
    - how_it_works/variable_set_up.md
    - how_it_works/provider_set_up.md
    - how_it_works/data_loading.md
    - how_it_works/data_aggregation.md
    - how_it_works/plotting.md
  - Virtual Environment:
    - virtual_env/index.md
  - Code Reference: reference/

plugins:
  - autorefs
  - search                          # Search bar
  - literate-nav:
      nav_file: SUMMARY.md          # To auto-generate paths
  - gen-files:
      scripts:
        - docs/scripts/pages_generator.py   # To auto generate 'Code Reference' Section
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy  # To parse docstrings
            docstring_section_style: spacy
            heading_level: 3
            show_root_toc_entry: false
            show_if_no_docstring: true
            showsubmodules: true


markdown_extensions:
  - admonition
  - pymdownx.superfences      # code blocks
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true   # Tabs
