site_name: BGC-DATA-PROCESSING
theme:
  name: "material"
  logo: assets/logo/NERSC.png
  favicon: assets/logo/NERSC.png
  palette:
    primary: blue
  features:
    - navigation.tabs               # Tabs
    - navigation.tabs.sticky        # Above tabs stay displayed
    - navigation.indexes            # Attach documents to sections
    - navigation.instant
    - navigation.top                # Scroll back to top button
    - watch:
        - "bgc_data_processing"

nav:
  - index.md
  - Projects:
    - projects/data_aggregator.md
    - projects/mapper.md
  - Virtual Environment: virtual_env.md
  - Code Reference: reference/

plugins:
  - autorefs
  - search                          # Search bar
  - literate-nav:
      nav_file: SUMMARY.md          # To auto-generate paths
  - gen-files:
      scripts:
        - docs/pages_generator.py   # To auto generate 'Code Reference' Section
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy  # To parse docstrings
            docstring_section_style: spacy
            heading_level: 3
            show_root_toc_entry: false
            show_if_no_docstring: true
            showsubmodules: true


markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
